### ISSUE TITLE
增加了一个纯pygame方式运行方法

### ISSUE THREAD

**Issue by edward32tnt** [halida/snake-challenge#20]
把蛇程序放到examples目录中，本来是想做成web提交的，感觉挺麻烦于是就直接用pygame了

```
class AI:
    def __init__(self):
        self.name = 'name'
        self.type = 'python' # or ruby

    def setmap(self, map):

    def step(self, info):
        return direction
```

程序会调用turn和set_map

比较简陋^_^

**Comment by edward32tnt** [comment]
欢迎测试

**Comment by ray58750034** [comment]
正是我想要的，great!

**Comment by edward32tnt** [comment]
样子还比较丑陋，呵呵

**Comment by davies** [comment]
û, ֮ǰѾpygame ʾô?

2011/6/29 edward32tnt <
reply@reply.github.com>

> ߳ŵexamplesĿ¼Уwebύģоͦ鷳Ǿֱpygame
> 
> ```
> class AI:
>    def __init__(self):
>        self.name = 'name'
>        self.type = 'python' # or ruby
> 
>    def set_map(self, map):
> 
>    def turn(self, info):
>        return direction
> ```
> 
> turnset_map
> 
> Ƚϼª^_^
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/halida/snake-challenge/issues/20

## 
- Davies

**Comment by edward32tnt** [comment]
乱码，davies

**Comment by davies** [comment]
我是直接用gmail回复的, 看来是github的bug. 

没看懂怎么用...

**Comment by edward32tnt** [comment]
哦， 就是运行only_pygame.py

选个地图 数字  1 2 3 4

然后import蛇

from ai_simple import AI

AI蛇提供setmap，step

**Comment by halida** [comment]
去掉了pygame支持, 就这样吧...
