### ISSUE TITLE
当蛇的身体把自己绕进去的时候, 会出现从身体里面穿出来的状况

### ISSUE THREAD

**Issue by halida** [halida/snake-challenge#21]
- 这种状况下蛇应该死掉的. 看看判断蛇碰撞的逻辑是否有问题. 
- 撞了蛇的话会死在下一步, 覆盖掉其他蛇的身体.

**Comment by ray58750034** [comment]
这是我的错， 因为现在步骤改为了蛇先动，再判断蛇有没有死， 所以我在检查蛇头所在点的其他点的时候要把自己的蛇头去掉。结果不知怎么，现在蛇碰到自己身体居然没有判断到。。。

我记得我有提交过修正的代码， 具体可以snake_game.py check_hit方法， 但我没测试过。

最近比较忙，抱歉不能花精力在这个项目上了，还请大家帮忙纠正。

**Comment by halida** [comment]
解掉了. 第2个问题可以容忍.
