### ISSUE TITLE
proposal: apply HTML5-boilerplate and upgrade to Rails3.1

### ISSUE THREAD

**Issue by gutenye** [halida/snake-challenge#22]
Rails 3.1 introduce some new features:  asset pipeline, Coffescript, Sass. 

if it upgrades to Rails3.1, the main problem is developping with Coffescript and Sass or the old one, javascript and css?

**Comment by halida** [comment]
你能保证运行没有问题就上吧. 只要不要引入node.js... 现有的东西已经太多了, 我去掉了一个pygame.

**Comment by halida** [comment]
你能保证运行没有问题就上吧. 只要不要引入node.js... 现有的东西已经太多了, 我去掉了一个pygame.

**Comment by gutenye** [comment]
ȵȵȰ, Ѿܸ...  Ұchatдº.

On Wed, Jul 6, 2011 at 8:43 AM, halida <
reply@reply.github.com>wrote:

> ܱ֤ûϰ. ֻҪҪnode.js... еĶѾ̫, ȥһpygame.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/halida/snake-challenge/issues/22#issuecomment-1508618

## 

Linux, Vim, Ruby, Lisp, Go, and English.
twitter: @gutenye

**Comment by halida** [comment]
乱码?

**Comment by gutenye** [comment]
那先等等吧, 现在已经很复杂了... chat 你实现了吗 不用node.

**Comment by halida** [comment]
我用tornado + websocket实现了一个简单的. 暂时用着吧.

**Comment by gutenye** [comment]
我先来干这个先。

**Comment by gutenye** [comment]
rails3.1 有些plugin没跟上 升级不了
