### ISSUE TITLE
don't put config/database.yml into version control

### ISSUE THREAD

**Issue by gutenye** [halida/snake-challenge#23]
config/database.yml 是个人配置文件。

对于第一次使用方法

```
git clone git@github.com:halida/snake-challenge.git 
cd snake-challenge/rubyweb
cp config/database.yml.example  config/database.yml
```

我删除过2次了...,  删除需要

```
git  rm config/database.yml
git commit -m 'delete database.yml'
# 其他人更新的时候要注意了, 别在把它再check in.
```

用GUI的git的人 可能需要， 右键 里面的设置吧.

thanks

**Comment by makestory** [comment]
把 rubyweb/config/database.yml
写进 .gitignore 就可以避免了。

另外应该把网站东西比如 GoogleAnalytics 的key等数据也单独存放不进版本管理。
放在比如 config/config.yml

@halida  把这个这帐号加到 commitor 里吧 （loddit）是我的新帐号，新电脑用的是这个，不然提交不了。

**Comment by gutenye** [comment]
不行的吧, 一但把database.yml add into version control,  即使写进.gitignore就不能避免了。 我测试是不行的

另外 
- Gemfile.lock不用写进.gitignore
- rubyweb 下面的东西写到 rubyweb/.gitignore里面, 不要写在外面的.gitignore.  方便管理

**Comment by halida** [comment]
database.yml我觉得就不要删除了, 默认localhost即可, 每个人应该都是用本地的, 没有什么区别的吧. 不然新的开发者还得改.
gitignore能import其他文件的吗? 如果可以的话可以用rubyweb/.gitignore的方式, guten你就这样改吧.

**Comment by gutenye** [comment]
en, 改了.gitignore了。

我开发是用sqlite3的，如果用mysql/postgresql的话,  username和password每个人都不一样的。

**Comment by makestory** [comment]
是这样  修改.gitignore之前就已经进入git的文件，是不会移出的，不过只要你 git rm 一下，以后 add . 时就不会再被添加到版本库了。
