### ISSUE TITLE
能否考虑一下网络比较差的情况？

### ISSUE THREAD

**Issue by jinleileiking** [halida/snake-challenge#24]
以前完时，如果网络差，几次不给命令，蛇就死了，

现在的版本有没有修复这个bug？

搞的我玩不了：（

**Comment by halida** [comment]
现在不自动踢人了. 并且也加了手动玩的方法. 但是转成websocket了, 还没有整上服务器.

**Comment by gutenye** [comment]
对于ai网络差的话 解决方法
- 把ai上传到server.
- 用socket进行连接.

**Comment by jinleileiking** [comment]
@GutenYe 

这个杂整？

就指着这个游戏消磨上班时间呢：）

**Comment by halida** [comment]
恩, 我再写个socket server, 然后你用socket来连?

**Comment by halida** [comment]
我还是先把新的程序整理好放上去吧, 不能太拖了...

**Comment by halida** [comment]
http://pythonvsruby.org:3467/ 这个暂时做了测试环境可以手动玩的... 需要先注册. 等我搞成正式的还得重新注册一遍...

**Comment by gutenye** [comment]
@halida

恩 ～ 再写个socket, 还要写个client Ruby API 给ai用~~  
工作量大了.....

**Comment by halida** [comment]
还行, 都是小接口程序.
