### ISSUE TITLE
登录的帐号能够统计胜负信息

### ISSUE THREAD

**Issue by gutenye** [halida/snake-challenge#5]
- 胜负情况

**Comment by halida** [comment]
这个不太好做吧.

**Comment by gutenye** [comment]
rails的界面做好了 需要game sever的zmq提供一个socket， 把每一局的胜负逃跑情况传给rails，然后存入到数据库里面. 或者在game serer端直接把胜负情况存入database.

ps. 本次更新 需要 rake db:reset; rake db:seed
