### ISSUE TITLE
Sprit 相关的参数应该体现在规则文档中

### ISSUE THREAD

**Issue by ftao** [halida/snake-challenge#55]
就是

SPRINT_ROUND = 5 
SPRINT_STEP = 3 # sprint的时候, 每轮可以走的步数
SPRINT_REST = 20 # sprint之后需要休息的时间

这个三个参数

**Comment by halida** [comment]
https://github.com/halida/snake-challenge/wiki/%E6%B8%B8%E6%88%8F%E8%A7%84%E5%88%99
done.
