### ISSUE TITLE
穿越portals以后蛇不能往回走

### ISSUE THREAD

**Issue by edward32tnt** [halida/snake-challenge#61]
比如我从方向【下】进入portal，然后从另一头出来的时候我不能选择方向【上】！

**Comment by resty-daze** [comment]
我觉得这样还算合理的，因为规则是不能往回走的

**Comment by edward32tnt** [comment]
普通的不能往回走是因为背后是身体，但是穿越了以后身体就不在身后了

**Comment by resty-daze** [comment]
规则上就是：蛇只能往前, 往左或者往右移动
如果只是因为背后是身体，那么应该可以往回走，只是会撞死吧

**Comment by edward32tnt** [comment]
没有这么说这个规则吧。你想多了

**Comment by resty-daze** [comment]
规则是wiki上写的，改的话记得改wiki

**Comment by halida** [comment]
我觉得还是从逻辑上看:
蛇不能往回走, 一方面是蛇身体挡着, 还有就是脖子的结构, 我不觉得蛇的脖子能够180度转, 也不太合理.
所以现在游戏的判断方式, 不能往后面方向走, 是合理的.
