### ISSUE TITLE
蛇的头经过传送门之后, 如何检查蛇是否往回走?

### ISSUE THREAD

**Issue by halida** [halida/snake-challenge#62]
逻辑上面, 应该是能够4个方向?

**Comment by edward32tnt** [comment]
对啊，现在是有检查的，问题是怎么弄成不检查的。

**Comment by halida** [comment]
我觉得还是从逻辑上看:
蛇不能往回走, 一方面是蛇身体挡着, 还有就是脖子的结构, 我不觉得蛇的脖子能够180度转, 也不太合理.
所以现在游戏的判断方式, 不能往后面方向走, 是合理的.

此issue在
https://github.com/halida/snake-challenge/issues/61
讨论.
