### ISSUE TITLE
在有Portal 的情况下，服务器端的noturnback 判断不正确

### ISSUE THREAD

**Issue by ftao** [halida/snake-challenge#65]
https://img.skitch.com/20111217-1ecti95jfgf2ri1hwtnqbfybpd.png

方向3  进入 (33, 19)
然后方向１ 进入 (16, 18) 

这个操作应该是合法的啊。　不应该认为非法操作。

**Comment by resty-daze** [comment]
参看这个
https://github.com/halida/snake-challenge/issues/61

**Comment by ftao** [comment]
好吧。　了解了。。

**Comment by edward32tnt** [comment]
其实我也觉得这个应该能走，但林君说蛇的脖子扭不过来
