### ISSUE TITLE
采用websocket来更新地图[server端]

### ISSUE THREAD

**Issue by gutenye** [halida/snake-challenge#9]
目前是ajax pull.

**Comment by halida** [comment]
现在是ajax pull 轮询的方式...
考虑到可能的实现方式, 另外一种是long pull, 但是鉴于rails server只有多进程模式靠谱, 这种方式有点走不通.
考虑了websocket, 对于改善延迟没有帮助, 但是可以利用websocket来让获取info变回long pull的模式减少性能损耗.

**Comment by makestory** [comment]
咱们那天讨论后，确实感觉显示游戏这部分的设计还是挺复杂，想在这里继续讨论下：

其实显示游戏系统应该是一个广播系统的模型（因为任何人在一个房间里看到的东西都应该是一样的）。
理想情况下是，服务器自己更新每一步的状态，然后向每一个客户端广播每回合的信息。
目前的ajax pull，想到有两点缺点， 
1 靠定时轮询，不能保证每一次轮询，服务器端只进行了一步，有可能发生跳步。
2 每一步都是由浏览器端去请求(网络延迟),每次服务都是处理http请求然后返回，相对耗时且浪费资源。

使用websocket由请求应答变为推送。把更多的调度设计放到了服务器端。设计可以灵活控制。
halida使用的协程是挺好的方案，启动一个服务从zmq获取每一步的信息，每一个websocket都从这个服务去取每一步的信息。这样就只有调用一次zmq连接，可以给各个websocket。 
tornado自带的websocket模块的message也能能实现广播的功能。
只有一个小问题是连接zmq仍然使用0.5秒间隔的轮询，还是有可能出现跳步的问题。这个可以通过调整zmq的时间或使用监听代替轮询可以解决。

halida的看法是？

**Comment by halida** [comment]
我已经写好了一个websocket的实现, 只是但是因为种种考虑没有整合进来. 今天晚上我会把代码放出来(还在我的小本里面)
在我的实现里面, 用tornado注册一个timeout的事件, 然后0.1秒轮询. 
理论上来说, 更好的方法是poll zmq的pub socket, 但是我不知道如何来做.

**Comment by halida** [comment]
我现在已经整好了poll zmq pub的方式了.
